# Generated by Django 4.2.7 on 2023-12-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_remove_goal_user_remove_transaction_user_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeapp.account'),
        ),
    ]
